# Generated by Django 4.2 on 2023-05-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_videomodel1_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel1',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
