# Generated by Django 4.2 on 2023-05-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_videomodel1_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='video')),
                ('img', models.ImageField(upload_to='img')),
                ('doc', models.FileField(upload_to='doc')),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='VideoModel1',
        ),
    ]
