# Generated by Django 4.2 on 2023-05-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_videomodel_delete_videomodel1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
