# Generated by Django 4.2 on 2023-05-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_videomodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='img',
            field=models.ImageField(upload_to='img', verbose_name='teacher photo'),
        ),
    ]
