# Generated by Django 4.2 on 2023-05-20 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_kursmodel_remove_videomodel_img_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KursModel',
            new_name='TeacherModel',
        ),
    ]
