# Generated by Django 4.2 on 2023-05-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_kursmodel_teachermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='img')),
                ('video', models.FileField(upload_to='video')),
                ('doc', models.FileField(upload_to='doc')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='ChatModel',
        ),
        migrations.RemoveField(
            model_name='videomodel',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='TeacherModel',
        ),
        migrations.DeleteModel(
            name='VideoModel',
        ),
    ]
